include:
  - remote: "https://gitlab.com/e-comm3692313/ci-template-repo/raw/main/.gitlab-ci.yml"

variables:
  PROJECT_NAME: "ETA-Stone-Free"
  PROJECT_TYPE: "backend" # Explicitly set (optional if requirements.txt exists)
  BACKEND_TEST_CMD: "pytest --junitxml=report.xml"
  BACKEND_BUILD_CMD: "make build env=deploy"
  ECS_CLUSTER: "backend-cluster"
  ECS_SERVICE: "backend-service"
  DEPLOYMENT_URL: "https://api.my-backend.com"
