# Generated by Django 4.2.8 on 2024-01-26 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_productimage_created_at_productimage_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='updated_at',
        ),
    ]
