# Generated by Django 4.2.20 on 2025-03-14 15:02

from django.db import migrations
import oscar.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_remove_productimage_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributeoption',
            name='code',
            field=oscar.models.fields.NullCharField(max_length=255, unique=True, verbose_name='Unique identifier'),
        ),
        migrations.AddField(
            model_name='attributeoptiongroup',
            name='code',
            field=oscar.models.fields.NullCharField(max_length=255, unique=True, verbose_name='Unique identifier'),
        ),
        migrations.AddField(
            model_name='category',
            name='code',
            field=oscar.models.fields.NullCharField(max_length=255, unique=True, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='code',
            field=oscar.models.fields.NullCharField(max_length=255, unique=True, verbose_name='Code'),
        ),
    ]
