# Generated by Django 4.2.8 on 2024-03-07 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_created_at_user_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
    ]
