version: "3.3"

volumes:
  postgres_data:
  volumes:
  static_volume:
  media_volume:
  certs:
  html:
  vhost:
  acme:

services:
  nginx-proxy:
    build:
      context: ../../
      dockerfile: docker/deploy/nginx/Dockerfile
    image: 336314182655.ap-southeast-2.compute.amazonaws.com/django-ec2:nginx
    container_name: nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - static_volume:/usr/src/django/src/public/static
      - media_volume:/usr/src/django/src/public/media
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      web-deploy:
        condition: service_started

  db-deploy:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - env/.env.db.prod

  web-deploy:
    image: 336314182655.ap-southeast-2.compute.amazonaws.com/django-ec2:web
    build:
      context: ../../
      dockerfile: docker/Dockerfile
    volumes:
      - ../../.:/usr/src/django
      - static_volume:/usr/src/django/src/public/static
      - media_volume:/usr/src/django/src/public/media
    env_file:
      - env/.env.django.prod
    working_dir: /usr/src/django/src
    container_name: web
    command: ["gunicorn", "settings.wsgi:application", "--bind", "0.0.0.0:8000"]
    ports:
      - 8080:8080
      - 8000:8000
